export const localUrl = "https://jrc-app-mftzj.ondigitalocean.app/api";
// export const localUrl = "http://localhost:8000/api";
// export const searchUrl = "https://20.242.247.247.nip.io/api/search/jobs";
export const searchUrl = "https://jrc-app-mftzj.ondigitalocean.app/api/jobs";
// export const searchUrl = "http://localhost:8000/api/jobs";
// export const recommendUrl = "https://20.242.247.247.nip.io/api/job-recommend/recommend-job";
export const recommendUrl = "https://20.204.216.47.nip.io/api/job-recommend/recommend/?user_id=";
export const readCVUrl = "https://20.204.216.47.nip.io/api/cv/read-cv";
export const checkImgUrl = "https://20.204.216.47.nip.io/api/cv/detect-faces";
export const relatedUrl = "https://20.204.216.47.nip.io/api/search/title?title=";
export const rateUrl = "https://20.204.216.47.nip.io/api/rate/update_data/";
export const getRateUrl = "https://20.204.216.47.nip.io/api/rate/get_rate/";
// export const localUrl = process.env.localUrl;
// export const searchUrl = process.env.searchUrl;
// export const recommendUrl = process.env.recommendUrl;
// export const readCVUrl = process.env.readCVUrl;
// export const relatedUrl = process.env.relatedUrl;
