export const localUrl = "https://jr-app-zyarc.ondigitalocean.app/api";
// export const localUrl = "http://localhost:8000/api";
export const searchUrl = "https://20.91.169.93.nip.io/api/server/jobs";
export const recommendUrl = "https://20.91.169.93.nip.io/api/server/recommend-job";
export const readCVUrl = "https://20.91.169.93.nip.io/api/cv/read-cv";
export const relatedUrl = "https://20.91.169.93.nip.io/api/server/title?title=";
// export const localUrl = process.env.localUrl;
// export const searchUrl = process.env.searchUrl;
// export const recommendUrl = process.env.recommendUrl;
// export const readCVUrl = process.env.readCVUrl;
// export const relatedUrl = process.env.relatedUrl;