repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: traefik
    url: https://traefik.github.io/charts
  - name: k8tz
    url: https://k8tz.github.io/k8tz

releases:
  - chart: jetstack/cert-manager
    name: cert-manager
    namespace: cert-manager
    version: v1.12.1
    # NOTE: Inline values, passed via a temporary values file
    values:
      - installCRDs: true
  - chart: traefik/traefik
    name: traefik
    namespace: kube-system
    version: 20.3.1
  - chart: k8tz/k8tz
    name: k8tz
    namespace: kube-system
    version: 0.13.0
    values:
      - timezone: UTC

helmDefaults:
  wait: false
  createNamespace: true
