apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-statefulset
  namespace: elasticsearch
spec:
  selector:
    matchLabels:
      app: elastic-statefulset
  serviceName: elastic-service
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic-statefulset
    spec:
      securityContext:
        fsGroup: 1001

      containers:
        - name: elastic-statefulset
          image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
          imagePullPolicy: Always
          env:
            - name: discovery.type
              value: single-node

          ports:
            - containerPort: 9200

          volumeMounts:
            - name: elastic-pvc
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: elastic-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
