apiVersion: v1
kind: Service
metadata:
  name: elastic-service
  namespace: elasticsearch
spec:
  selector:
    app: elastic-statefulset
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
